version: "3.8"

services:
  app:
    build: .
    ports:
      - "8800:8800"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/hotel-booking
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
